// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// NewPostAPIPublicV1IncidentsParams creates a new PostAPIPublicV1IncidentsParams object
// with the default values initialized.
func NewPostAPIPublicV1IncidentsParams() *PostAPIPublicV1IncidentsParams {
	var ()
	return &PostAPIPublicV1IncidentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIPublicV1IncidentsParamsWithTimeout creates a new PostAPIPublicV1IncidentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIPublicV1IncidentsParamsWithTimeout(timeout time.Duration) *PostAPIPublicV1IncidentsParams {
	var ()
	return &PostAPIPublicV1IncidentsParams{

		timeout: timeout,
	}
}

// NewPostAPIPublicV1IncidentsParamsWithContext creates a new PostAPIPublicV1IncidentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIPublicV1IncidentsParamsWithContext(ctx context.Context) *PostAPIPublicV1IncidentsParams {
	var ()
	return &PostAPIPublicV1IncidentsParams{

		Context: ctx,
	}
}

// NewPostAPIPublicV1IncidentsParamsWithHTTPClient creates a new PostAPIPublicV1IncidentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIPublicV1IncidentsParamsWithHTTPClient(client *http.Client) *PostAPIPublicV1IncidentsParams {
	var ()
	return &PostAPIPublicV1IncidentsParams{
		HTTPClient: client,
	}
}

/*PostAPIPublicV1IncidentsParams contains all the parameters to send to the API endpoint
for the post API public v1 incidents operation typically these are written to a http.Request
*/
type PostAPIPublicV1IncidentsParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Body
	  The incident details

	*/
	Body *models.CreateIncidentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithTimeout(timeout time.Duration) *PostAPIPublicV1IncidentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithContext(ctx context.Context) *PostAPIPublicV1IncidentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithHTTPClient(client *http.Client) *PostAPIPublicV1IncidentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithXVOAPIID(xVOAPIID string) *PostAPIPublicV1IncidentsParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithXVOAPIKey(xVOAPIKey string) *PostAPIPublicV1IncidentsParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithBody adds the body to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) WithBody(body *models.CreateIncidentRequest) *PostAPIPublicV1IncidentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API public v1 incidents params
func (o *PostAPIPublicV1IncidentsParams) SetBody(body *models.CreateIncidentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIPublicV1IncidentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
