// Code generated by go-swagger; DO NOT EDIT.

package personal_paging_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParams creates a new GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams object
// with the default values initialized.
func NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParams() *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithTimeout creates a new GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithTimeout(timeout time.Duration) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams{

		timeout: timeout,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithContext creates a new GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithContext(ctx context.Context) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams{

		Context: ctx,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithHTTPClient creates a new GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIPublicV1ProfileUsernamePoliciesStepRuleParamsWithHTTPClient(client *http.Client) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams{
		HTTPClient: client,
	}
}

/*GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams contains all the parameters to send to the API endpoint
for the get API public v1 profile username policies step rule operation typically these are written to a http.Request
*/
type GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Rule
	  Rule for a paging policy step

	*/
	Rule float64
	/*Step
	  Paging policy step

	*/
	Step float64
	/*Username
	  Your username

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithTimeout(timeout time.Duration) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithContext(ctx context.Context) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithHTTPClient(client *http.Client) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithXVOAPIID(xVOAPIID string) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithXVOAPIKey(xVOAPIKey string) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithRule adds the rule to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithRule(rule float64) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetRule(rule float64) {
	o.Rule = rule
}

// WithStep adds the step to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithStep(step float64) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetStep(step)
	return o
}

// SetStep adds the step to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetStep(step float64) {
	o.Step = step
}

// WithUsername adds the username to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WithUsername(username string) *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get API public v1 profile username policies step rule params
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIPublicV1ProfileUsernamePoliciesStepRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	// path param rule
	if err := r.SetPathParam("rule", swag.FormatFloat64(o.Rule)); err != nil {
		return err
	}

	// path param step
	if err := r.SetPathParam("step", swag.FormatFloat64(o.Step)); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
