// Code generated by go-swagger; DO NOT EDIT.

package personal_paging_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIPublicV1ProfileUsernamePoliciesParams creates a new GetAPIPublicV1ProfileUsernamePoliciesParams object
// with the default values initialized.
func NewGetAPIPublicV1ProfileUsernamePoliciesParams() *GetAPIPublicV1ProfileUsernamePoliciesParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithTimeout creates a new GetAPIPublicV1ProfileUsernamePoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithTimeout(timeout time.Duration) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesParams{

		timeout: timeout,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithContext creates a new GetAPIPublicV1ProfileUsernamePoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithContext(ctx context.Context) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesParams{

		Context: ctx,
	}
}

// NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithHTTPClient creates a new GetAPIPublicV1ProfileUsernamePoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIPublicV1ProfileUsernamePoliciesParamsWithHTTPClient(client *http.Client) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	var ()
	return &GetAPIPublicV1ProfileUsernamePoliciesParams{
		HTTPClient: client,
	}
}

/*GetAPIPublicV1ProfileUsernamePoliciesParams contains all the parameters to send to the API endpoint
for the get API public v1 profile username policies operation typically these are written to a http.Request
*/
type GetAPIPublicV1ProfileUsernamePoliciesParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Username
	  Your username

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithTimeout(timeout time.Duration) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithContext(ctx context.Context) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithHTTPClient(client *http.Client) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithXVOAPIID(xVOAPIID string) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithXVOAPIKey(xVOAPIKey string) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithUsername adds the username to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WithUsername(username string) *GetAPIPublicV1ProfileUsernamePoliciesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get API public v1 profile username policies params
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIPublicV1ProfileUsernamePoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
