// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAPIPublicV1UserUserReader is a Reader for the DeleteAPIPublicV1UserUser structure.
type DeleteAPIPublicV1UserUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIPublicV1UserUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAPIPublicV1UserUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteAPIPublicV1UserUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteAPIPublicV1UserUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAPIPublicV1UserUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAPIPublicV1UserUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewDeleteAPIPublicV1UserUserUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteAPIPublicV1UserUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIPublicV1UserUserOK creates a DeleteAPIPublicV1UserUserOK with default headers values
func NewDeleteAPIPublicV1UserUserOK() *DeleteAPIPublicV1UserUserOK {
	return &DeleteAPIPublicV1UserUserOK{}
}

/*DeleteAPIPublicV1UserUserOK handles this case with default header values.

User was deleted
*/
type DeleteAPIPublicV1UserUserOK struct {
}

func (o *DeleteAPIPublicV1UserUserOK) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserOK ", 200)
}

func (o *DeleteAPIPublicV1UserUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserBadRequest creates a DeleteAPIPublicV1UserUserBadRequest with default headers values
func NewDeleteAPIPublicV1UserUserBadRequest() *DeleteAPIPublicV1UserUserBadRequest {
	return &DeleteAPIPublicV1UserUserBadRequest{}
}

/*DeleteAPIPublicV1UserUserBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type DeleteAPIPublicV1UserUserBadRequest struct {
}

func (o *DeleteAPIPublicV1UserUserBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserBadRequest ", 400)
}

func (o *DeleteAPIPublicV1UserUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserUnauthorized creates a DeleteAPIPublicV1UserUserUnauthorized with default headers values
func NewDeleteAPIPublicV1UserUserUnauthorized() *DeleteAPIPublicV1UserUserUnauthorized {
	return &DeleteAPIPublicV1UserUserUnauthorized{}
}

/*DeleteAPIPublicV1UserUserUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type DeleteAPIPublicV1UserUserUnauthorized struct {
}

func (o *DeleteAPIPublicV1UserUserUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserUnauthorized ", 401)
}

func (o *DeleteAPIPublicV1UserUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserForbidden creates a DeleteAPIPublicV1UserUserForbidden with default headers values
func NewDeleteAPIPublicV1UserUserForbidden() *DeleteAPIPublicV1UserUserForbidden {
	return &DeleteAPIPublicV1UserUserForbidden{}
}

/*DeleteAPIPublicV1UserUserForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type DeleteAPIPublicV1UserUserForbidden struct {
}

func (o *DeleteAPIPublicV1UserUserForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserForbidden ", 403)
}

func (o *DeleteAPIPublicV1UserUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserNotFound creates a DeleteAPIPublicV1UserUserNotFound with default headers values
func NewDeleteAPIPublicV1UserUserNotFound() *DeleteAPIPublicV1UserUserNotFound {
	return &DeleteAPIPublicV1UserUserNotFound{}
}

/*DeleteAPIPublicV1UserUserNotFound handles this case with default header values.

User not found
*/
type DeleteAPIPublicV1UserUserNotFound struct {
}

func (o *DeleteAPIPublicV1UserUserNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserNotFound ", 404)
}

func (o *DeleteAPIPublicV1UserUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserUnprocessableEntity creates a DeleteAPIPublicV1UserUserUnprocessableEntity with default headers values
func NewDeleteAPIPublicV1UserUserUnprocessableEntity() *DeleteAPIPublicV1UserUserUnprocessableEntity {
	return &DeleteAPIPublicV1UserUserUnprocessableEntity{}
}

/*DeleteAPIPublicV1UserUserUnprocessableEntity handles this case with default header values.

There was a problem with the delete such as the replacement user was not found.

*/
type DeleteAPIPublicV1UserUserUnprocessableEntity struct {
}

func (o *DeleteAPIPublicV1UserUserUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserUnprocessableEntity ", 422)
}

func (o *DeleteAPIPublicV1UserUserUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserInternalServerError creates a DeleteAPIPublicV1UserUserInternalServerError with default headers values
func NewDeleteAPIPublicV1UserUserInternalServerError() *DeleteAPIPublicV1UserUserInternalServerError {
	return &DeleteAPIPublicV1UserUserInternalServerError{}
}

/*DeleteAPIPublicV1UserUserInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteAPIPublicV1UserUserInternalServerError struct {
}

func (o *DeleteAPIPublicV1UserUserInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}][%d] deleteApiPublicV1UserUserInternalServerError ", 500)
}

func (o *DeleteAPIPublicV1UserUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
