// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIPublicV1UserReader is a Reader for the GetAPIPublicV1User structure.
type GetAPIPublicV1UserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPublicV1UserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIPublicV1UserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIPublicV1UserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIPublicV1UserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIPublicV1UserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIPublicV1UserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewGetAPIPublicV1UserUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIPublicV1UserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIPublicV1UserOK creates a GetAPIPublicV1UserOK with default headers values
func NewGetAPIPublicV1UserOK() *GetAPIPublicV1UserOK {
	return &GetAPIPublicV1UserOK{}
}

/*GetAPIPublicV1UserOK handles this case with default header values.

A list of users for your organization
*/
type GetAPIPublicV1UserOK struct {
	Payload *models.ListUserResponse
}

func (o *GetAPIPublicV1UserOK) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserOK  %+v", 200, o.Payload)
}

func (o *GetAPIPublicV1UserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPublicV1UserBadRequest creates a GetAPIPublicV1UserBadRequest with default headers values
func NewGetAPIPublicV1UserBadRequest() *GetAPIPublicV1UserBadRequest {
	return &GetAPIPublicV1UserBadRequest{}
}

/*GetAPIPublicV1UserBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIPublicV1UserBadRequest struct {
}

func (o *GetAPIPublicV1UserBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserBadRequest ", 400)
}

func (o *GetAPIPublicV1UserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserUnauthorized creates a GetAPIPublicV1UserUnauthorized with default headers values
func NewGetAPIPublicV1UserUnauthorized() *GetAPIPublicV1UserUnauthorized {
	return &GetAPIPublicV1UserUnauthorized{}
}

/*GetAPIPublicV1UserUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIPublicV1UserUnauthorized struct {
}

func (o *GetAPIPublicV1UserUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserUnauthorized ", 401)
}

func (o *GetAPIPublicV1UserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserForbidden creates a GetAPIPublicV1UserForbidden with default headers values
func NewGetAPIPublicV1UserForbidden() *GetAPIPublicV1UserForbidden {
	return &GetAPIPublicV1UserForbidden{}
}

/*GetAPIPublicV1UserForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIPublicV1UserForbidden struct {
}

func (o *GetAPIPublicV1UserForbidden) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserForbidden ", 403)
}

func (o *GetAPIPublicV1UserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserNotFound creates a GetAPIPublicV1UserNotFound with default headers values
func NewGetAPIPublicV1UserNotFound() *GetAPIPublicV1UserNotFound {
	return &GetAPIPublicV1UserNotFound{}
}

/*GetAPIPublicV1UserNotFound handles this case with default header values.

User not found
*/
type GetAPIPublicV1UserNotFound struct {
}

func (o *GetAPIPublicV1UserNotFound) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserNotFound ", 404)
}

func (o *GetAPIPublicV1UserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserUnprocessableEntity creates a GetAPIPublicV1UserUnprocessableEntity with default headers values
func NewGetAPIPublicV1UserUnprocessableEntity() *GetAPIPublicV1UserUnprocessableEntity {
	return &GetAPIPublicV1UserUnprocessableEntity{}
}

/*GetAPIPublicV1UserUnprocessableEntity handles this case with default header values.

You have reached your user limit.

*/
type GetAPIPublicV1UserUnprocessableEntity struct {
}

func (o *GetAPIPublicV1UserUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserUnprocessableEntity ", 422)
}

func (o *GetAPIPublicV1UserUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserInternalServerError creates a GetAPIPublicV1UserInternalServerError with default headers values
func NewGetAPIPublicV1UserInternalServerError() *GetAPIPublicV1UserInternalServerError {
	return &GetAPIPublicV1UserInternalServerError{}
}

/*GetAPIPublicV1UserInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIPublicV1UserInternalServerError struct {
}

func (o *GetAPIPublicV1UserInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user][%d] getApiPublicV1UserInternalServerError ", 500)
}

func (o *GetAPIPublicV1UserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
