// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// PutAPIPublicV1UserUserReader is a Reader for the PutAPIPublicV1UserUser structure.
type PutAPIPublicV1UserUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIPublicV1UserUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAPIPublicV1UserUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutAPIPublicV1UserUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPutAPIPublicV1UserUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPutAPIPublicV1UserUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutAPIPublicV1UserUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewPutAPIPublicV1UserUserUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPutAPIPublicV1UserUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAPIPublicV1UserUserOK creates a PutAPIPublicV1UserUserOK with default headers values
func NewPutAPIPublicV1UserUserOK() *PutAPIPublicV1UserUserOK {
	return &PutAPIPublicV1UserUserOK{}
}

/*PutAPIPublicV1UserUserOK handles this case with default header values.

Some details about the user that was added
*/
type PutAPIPublicV1UserUserOK struct {
	Payload *models.AddUserResponse
}

func (o *PutAPIPublicV1UserUserOK) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserOK  %+v", 200, o.Payload)
}

func (o *PutAPIPublicV1UserUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPIPublicV1UserUserBadRequest creates a PutAPIPublicV1UserUserBadRequest with default headers values
func NewPutAPIPublicV1UserUserBadRequest() *PutAPIPublicV1UserUserBadRequest {
	return &PutAPIPublicV1UserUserBadRequest{}
}

/*PutAPIPublicV1UserUserBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type PutAPIPublicV1UserUserBadRequest struct {
}

func (o *PutAPIPublicV1UserUserBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserBadRequest ", 400)
}

func (o *PutAPIPublicV1UserUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIPublicV1UserUserUnauthorized creates a PutAPIPublicV1UserUserUnauthorized with default headers values
func NewPutAPIPublicV1UserUserUnauthorized() *PutAPIPublicV1UserUserUnauthorized {
	return &PutAPIPublicV1UserUserUnauthorized{}
}

/*PutAPIPublicV1UserUserUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type PutAPIPublicV1UserUserUnauthorized struct {
}

func (o *PutAPIPublicV1UserUserUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserUnauthorized ", 401)
}

func (o *PutAPIPublicV1UserUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIPublicV1UserUserForbidden creates a PutAPIPublicV1UserUserForbidden with default headers values
func NewPutAPIPublicV1UserUserForbidden() *PutAPIPublicV1UserUserForbidden {
	return &PutAPIPublicV1UserUserForbidden{}
}

/*PutAPIPublicV1UserUserForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type PutAPIPublicV1UserUserForbidden struct {
}

func (o *PutAPIPublicV1UserUserForbidden) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserForbidden ", 403)
}

func (o *PutAPIPublicV1UserUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIPublicV1UserUserNotFound creates a PutAPIPublicV1UserUserNotFound with default headers values
func NewPutAPIPublicV1UserUserNotFound() *PutAPIPublicV1UserUserNotFound {
	return &PutAPIPublicV1UserUserNotFound{}
}

/*PutAPIPublicV1UserUserNotFound handles this case with default header values.

User not found
*/
type PutAPIPublicV1UserUserNotFound struct {
}

func (o *PutAPIPublicV1UserUserNotFound) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserNotFound ", 404)
}

func (o *PutAPIPublicV1UserUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIPublicV1UserUserUnprocessableEntity creates a PutAPIPublicV1UserUserUnprocessableEntity with default headers values
func NewPutAPIPublicV1UserUserUnprocessableEntity() *PutAPIPublicV1UserUserUnprocessableEntity {
	return &PutAPIPublicV1UserUserUnprocessableEntity{}
}

/*PutAPIPublicV1UserUserUnprocessableEntity handles this case with default header values.

Username or email is unavailable, or you have reached your user limit.

*/
type PutAPIPublicV1UserUserUnprocessableEntity struct {
}

func (o *PutAPIPublicV1UserUserUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserUnprocessableEntity ", 422)
}

func (o *PutAPIPublicV1UserUserUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutAPIPublicV1UserUserInternalServerError creates a PutAPIPublicV1UserUserInternalServerError with default headers values
func NewPutAPIPublicV1UserUserInternalServerError() *PutAPIPublicV1UserUserInternalServerError {
	return &PutAPIPublicV1UserUserInternalServerError{}
}

/*PutAPIPublicV1UserUserInternalServerError handles this case with default header values.

Internal Server Error
*/
type PutAPIPublicV1UserUserInternalServerError struct {
}

func (o *PutAPIPublicV1UserUserInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api-public/v1/user/{user}][%d] putApiPublicV1UserUserInternalServerError ", 500)
}

func (o *PutAPIPublicV1UserUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
