// Code generated by go-swagger; DO NOT EDIT.

package user_contact_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDReader is a Reader for the DeleteAPIPublicV1UserUserContactMethodsDevicesContactID structure.
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK handles this case with default header values.

Deleted contact device for the user
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK struct {
	Payload *models.ContactDevice
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContactDevice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdBadRequest ", 400)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdUnauthorized ", 401)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdForbidden ", 403)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound handles this case with default header values.

User not found
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdNotFound ", 404)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError creates a DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError() *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError {
	return &DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError{}
}

/*DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/devices/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsDevicesContactIdInternalServerError ", 500)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsDevicesContactIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
