// Code generated by go-swagger; DO NOT EDIT.

package user_contact_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDReader is a Reader for the DeleteAPIPublicV1UserUserContactMethodsEmailsContactID structure.
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK handles this case with default header values.

Deleted contact email for the user
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK struct {
	Payload *models.UserContact
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdOK  %+v", 200, o.Payload)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserContact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdBadRequest ", 400)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdUnauthorized ", 401)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdForbidden ", 403)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound handles this case with default header values.

User not found
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdNotFound ", 404)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError creates a DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError with default headers values
func NewDeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError() *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError {
	return &DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError{}
}

/*DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError struct {
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api-public/v1/user/{user}/contact-methods/emails/{contactId}][%d] deleteApiPublicV1UserUserContactMethodsEmailsContactIdInternalServerError ", 500)
}

func (o *DeleteAPIPublicV1UserUserContactMethodsEmailsContactIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
