// Code generated by go-swagger; DO NOT EDIT.

package user_contact_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIPublicV1UserUserContactMethodsPhonesContactIDReader is a Reader for the GetAPIPublicV1UserUserContactMethodsPhonesContactID structure.
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDOK creates a GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK with default headers values
func NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDOK() *GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK {
	return &GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK{}
}

/*GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK handles this case with default header values.

The indicated contact phone for the user
*/
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK struct {
	Payload []*models.UserContact
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user/{user}/contact-methods/phones/{contactId}][%d] getApiPublicV1UserUserContactMethodsPhonesContactIdOK  %+v", 200, o.Payload)
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized creates a GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized with default headers values
func NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized() *GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized {
	return &GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized{}
}

/*GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized struct {
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user/{user}/contact-methods/phones/{contactId}][%d] getApiPublicV1UserUserContactMethodsPhonesContactIdUnauthorized ", 401)
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden creates a GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden with default headers values
func NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden() *GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden {
	return &GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden{}
}

/*GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden struct {
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user/{user}/contact-methods/phones/{contactId}][%d] getApiPublicV1UserUserContactMethodsPhonesContactIdForbidden ", 403)
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound creates a GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound with default headers values
func NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound() *GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound {
	return &GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound{}
}

/*GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound handles this case with default header values.

User not found
*/
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound struct {
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user/{user}/contact-methods/phones/{contactId}][%d] getApiPublicV1UserUserContactMethodsPhonesContactIdNotFound ", 404)
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError creates a GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError with default headers values
func NewGetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError() *GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError {
	return &GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError{}
}

/*GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError struct {
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/user/{user}/contact-methods/phones/{contactId}][%d] getApiPublicV1UserUserContactMethodsPhonesContactIdInternalServerError ", 500)
}

func (o *GetAPIPublicV1UserUserContactMethodsPhonesContactIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
