// Code generated by go-swagger; DO NOT EDIT.

package user_contact_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// NewPostAPIPublicV1UserUserContactMethodsPhonesParams creates a new PostAPIPublicV1UserUserContactMethodsPhonesParams object
// with the default values initialized.
func NewPostAPIPublicV1UserUserContactMethodsPhonesParams() *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	var ()
	return &PostAPIPublicV1UserUserContactMethodsPhonesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithTimeout creates a new PostAPIPublicV1UserUserContactMethodsPhonesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithTimeout(timeout time.Duration) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	var ()
	return &PostAPIPublicV1UserUserContactMethodsPhonesParams{

		timeout: timeout,
	}
}

// NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithContext creates a new PostAPIPublicV1UserUserContactMethodsPhonesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithContext(ctx context.Context) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	var ()
	return &PostAPIPublicV1UserUserContactMethodsPhonesParams{

		Context: ctx,
	}
}

// NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithHTTPClient creates a new PostAPIPublicV1UserUserContactMethodsPhonesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIPublicV1UserUserContactMethodsPhonesParamsWithHTTPClient(client *http.Client) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	var ()
	return &PostAPIPublicV1UserUserContactMethodsPhonesParams{
		HTTPClient: client,
	}
}

/*PostAPIPublicV1UserUserContactMethodsPhonesParams contains all the parameters to send to the API endpoint
for the post API public v1 user user contact methods phones operation typically these are written to a http.Request
*/
type PostAPIPublicV1UserUserContactMethodsPhonesParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Body
	  The contact phone

	*/
	Body *models.ContactPhoneAdd
	/*User
	  The VictorOps user ID

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithTimeout(timeout time.Duration) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithContext(ctx context.Context) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithHTTPClient(client *http.Client) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithXVOAPIID(xVOAPIID string) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithXVOAPIKey(xVOAPIKey string) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithBody adds the body to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithBody(body *models.ContactPhoneAdd) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetBody(body *models.ContactPhoneAdd) {
	o.Body = body
}

// WithUser adds the user to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WithUser(user string) *PostAPIPublicV1UserUserContactMethodsPhonesParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the post API public v1 user user contact methods phones params
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIPublicV1UserUserContactMethodsPhonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
