// Code generated by go-swagger; DO NOT EDIT.

package user_contact_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParams creates a new PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams object
// with the default values initialized.
func NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParams() *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	var ()
	return &PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithTimeout creates a new PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithTimeout(timeout time.Duration) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	var ()
	return &PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams{

		timeout: timeout,
	}
}

// NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithContext creates a new PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithContext(ctx context.Context) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	var ()
	return &PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams{

		Context: ctx,
	}
}

// NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithHTTPClient creates a new PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIPublicV1UserUserContactMethodsDevicesContactIDParamsWithHTTPClient(client *http.Client) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	var ()
	return &PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams{
		HTTPClient: client,
	}
}

/*PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams contains all the parameters to send to the API endpoint
for the put API public v1 user user contact methods devices contact ID operation typically these are written to a http.Request
*/
type PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Body
	  The contact device

	*/
	Body *models.ContactDeviceAdd
	/*ContactID
	  The unique contact identifier

	*/
	ContactID string
	/*User
	  The VictorOps user ID

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithTimeout(timeout time.Duration) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithContext(ctx context.Context) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithHTTPClient(client *http.Client) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithXVOAPIID(xVOAPIID string) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithXVOAPIKey(xVOAPIKey string) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithBody adds the body to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithBody(body *models.ContactDeviceAdd) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetBody(body *models.ContactDeviceAdd) {
	o.Body = body
}

// WithContactID adds the contactID to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithContactID(contactID string) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetContactID(contactID)
	return o
}

// SetContactID adds the contactId to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetContactID(contactID string) {
	o.ContactID = contactID
}

// WithUser adds the user to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WithUser(user string) *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the put API public v1 user user contact methods devices contact ID params
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIPublicV1UserUserContactMethodsDevicesContactIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param contactId
	if err := r.SetPathParam("contactId", o.ContactID); err != nil {
		return err
	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
