// Code generated by go-swagger; DO NOT EDIT.

package personal_paging_policy_values

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIPublicV1PoliciesTypesContactsReader is a Reader for the GetAPIPublicV1PoliciesTypesContacts structure.
type GetAPIPublicV1PoliciesTypesContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPublicV1PoliciesTypesContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIPublicV1PoliciesTypesContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIPublicV1PoliciesTypesContactsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIPublicV1PoliciesTypesContactsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIPublicV1PoliciesTypesContactsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIPublicV1PoliciesTypesContactsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIPublicV1PoliciesTypesContactsOK creates a GetAPIPublicV1PoliciesTypesContactsOK with default headers values
func NewGetAPIPublicV1PoliciesTypesContactsOK() *GetAPIPublicV1PoliciesTypesContactsOK {
	return &GetAPIPublicV1PoliciesTypesContactsOK{}
}

/*GetAPIPublicV1PoliciesTypesContactsOK handles this case with default header values.

All the available contact types
*/
type GetAPIPublicV1PoliciesTypesContactsOK struct {
	Payload *models.GetAPIPublicV1PoliciesTypesContactsOKBody
}

func (o *GetAPIPublicV1PoliciesTypesContactsOK) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/policies/types/contacts][%d] getApiPublicV1PoliciesTypesContactsOK  %+v", 200, o.Payload)
}

func (o *GetAPIPublicV1PoliciesTypesContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetAPIPublicV1PoliciesTypesContactsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPublicV1PoliciesTypesContactsBadRequest creates a GetAPIPublicV1PoliciesTypesContactsBadRequest with default headers values
func NewGetAPIPublicV1PoliciesTypesContactsBadRequest() *GetAPIPublicV1PoliciesTypesContactsBadRequest {
	return &GetAPIPublicV1PoliciesTypesContactsBadRequest{}
}

/*GetAPIPublicV1PoliciesTypesContactsBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIPublicV1PoliciesTypesContactsBadRequest struct {
}

func (o *GetAPIPublicV1PoliciesTypesContactsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/policies/types/contacts][%d] getApiPublicV1PoliciesTypesContactsBadRequest ", 400)
}

func (o *GetAPIPublicV1PoliciesTypesContactsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1PoliciesTypesContactsUnauthorized creates a GetAPIPublicV1PoliciesTypesContactsUnauthorized with default headers values
func NewGetAPIPublicV1PoliciesTypesContactsUnauthorized() *GetAPIPublicV1PoliciesTypesContactsUnauthorized {
	return &GetAPIPublicV1PoliciesTypesContactsUnauthorized{}
}

/*GetAPIPublicV1PoliciesTypesContactsUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIPublicV1PoliciesTypesContactsUnauthorized struct {
}

func (o *GetAPIPublicV1PoliciesTypesContactsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/policies/types/contacts][%d] getApiPublicV1PoliciesTypesContactsUnauthorized ", 401)
}

func (o *GetAPIPublicV1PoliciesTypesContactsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1PoliciesTypesContactsForbidden creates a GetAPIPublicV1PoliciesTypesContactsForbidden with default headers values
func NewGetAPIPublicV1PoliciesTypesContactsForbidden() *GetAPIPublicV1PoliciesTypesContactsForbidden {
	return &GetAPIPublicV1PoliciesTypesContactsForbidden{}
}

/*GetAPIPublicV1PoliciesTypesContactsForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIPublicV1PoliciesTypesContactsForbidden struct {
}

func (o *GetAPIPublicV1PoliciesTypesContactsForbidden) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/policies/types/contacts][%d] getApiPublicV1PoliciesTypesContactsForbidden ", 403)
}

func (o *GetAPIPublicV1PoliciesTypesContactsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1PoliciesTypesContactsInternalServerError creates a GetAPIPublicV1PoliciesTypesContactsInternalServerError with default headers values
func NewGetAPIPublicV1PoliciesTypesContactsInternalServerError() *GetAPIPublicV1PoliciesTypesContactsInternalServerError {
	return &GetAPIPublicV1PoliciesTypesContactsInternalServerError{}
}

/*GetAPIPublicV1PoliciesTypesContactsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIPublicV1PoliciesTypesContactsInternalServerError struct {
}

func (o *GetAPIPublicV1PoliciesTypesContactsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/policies/types/contacts][%d] getApiPublicV1PoliciesTypesContactsInternalServerError ", 500)
}

func (o *GetAPIPublicV1PoliciesTypesContactsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
