// Code generated by go-swagger; DO NOT EDIT.

package on_call

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIPublicV2UserUserOncallScheduleParams creates a new GetAPIPublicV2UserUserOncallScheduleParams object
// with the default values initialized.
func NewGetAPIPublicV2UserUserOncallScheduleParams() *GetAPIPublicV2UserUserOncallScheduleParams {
	var (
		daysForwardDefault = float64(14)
		daysSkipDefault    = float64(0)
		stepDefault        = float64(0)
	)
	return &GetAPIPublicV2UserUserOncallScheduleParams{
		DaysForward: &daysForwardDefault,
		DaysSkip:    &daysSkipDefault,
		Step:        &stepDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIPublicV2UserUserOncallScheduleParamsWithTimeout creates a new GetAPIPublicV2UserUserOncallScheduleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIPublicV2UserUserOncallScheduleParamsWithTimeout(timeout time.Duration) *GetAPIPublicV2UserUserOncallScheduleParams {
	var (
		daysForwardDefault = float64(14)
		daysSkipDefault    = float64(0)
		stepDefault        = float64(0)
	)
	return &GetAPIPublicV2UserUserOncallScheduleParams{
		DaysForward: &daysForwardDefault,
		DaysSkip:    &daysSkipDefault,
		Step:        &stepDefault,

		timeout: timeout,
	}
}

// NewGetAPIPublicV2UserUserOncallScheduleParamsWithContext creates a new GetAPIPublicV2UserUserOncallScheduleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIPublicV2UserUserOncallScheduleParamsWithContext(ctx context.Context) *GetAPIPublicV2UserUserOncallScheduleParams {
	var (
		daysForwardDefault = float64(14)
		daysSkipDefault    = float64(0)
		stepDefault        = float64(0)
	)
	return &GetAPIPublicV2UserUserOncallScheduleParams{
		DaysForward: &daysForwardDefault,
		DaysSkip:    &daysSkipDefault,
		Step:        &stepDefault,

		Context: ctx,
	}
}

// NewGetAPIPublicV2UserUserOncallScheduleParamsWithHTTPClient creates a new GetAPIPublicV2UserUserOncallScheduleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIPublicV2UserUserOncallScheduleParamsWithHTTPClient(client *http.Client) *GetAPIPublicV2UserUserOncallScheduleParams {
	var (
		daysForwardDefault = float64(14)
		daysSkipDefault    = float64(0)
		stepDefault        = float64(0)
	)
	return &GetAPIPublicV2UserUserOncallScheduleParams{
		DaysForward: &daysForwardDefault,
		DaysSkip:    &daysSkipDefault,
		Step:        &stepDefault,
		HTTPClient:  client,
	}
}

/*GetAPIPublicV2UserUserOncallScheduleParams contains all the parameters to send to the API endpoint
for the get API public v2 user user oncall schedule operation typically these are written to a http.Request
*/
type GetAPIPublicV2UserUserOncallScheduleParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*DaysForward
	  Days to include in returned schedule (30 max)

	*/
	DaysForward *float64
	/*DaysSkip
	  Days to skip before computing schedule to return (90 max)

	*/
	DaysSkip *float64
	/*Step
	  Step of escalation policy (3 max)

	*/
	Step *float64
	/*User
	  The VictorOps user ID

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithTimeout(timeout time.Duration) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithContext(ctx context.Context) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithHTTPClient(client *http.Client) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithXVOAPIID(xVOAPIID string) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithXVOAPIKey(xVOAPIKey string) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithDaysForward adds the daysForward to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithDaysForward(daysForward *float64) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetDaysForward(daysForward)
	return o
}

// SetDaysForward adds the daysForward to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetDaysForward(daysForward *float64) {
	o.DaysForward = daysForward
}

// WithDaysSkip adds the daysSkip to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithDaysSkip(daysSkip *float64) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetDaysSkip(daysSkip)
	return o
}

// SetDaysSkip adds the daysSkip to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetDaysSkip(daysSkip *float64) {
	o.DaysSkip = daysSkip
}

// WithStep adds the step to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithStep(step *float64) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetStep(step)
	return o
}

// SetStep adds the step to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetStep(step *float64) {
	o.Step = step
}

// WithUser adds the user to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WithUser(user string) *GetAPIPublicV2UserUserOncallScheduleParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get API public v2 user user oncall schedule params
func (o *GetAPIPublicV2UserUserOncallScheduleParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIPublicV2UserUserOncallScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	if o.DaysForward != nil {

		// query param daysForward
		var qrDaysForward float64
		if o.DaysForward != nil {
			qrDaysForward = *o.DaysForward
		}
		qDaysForward := swag.FormatFloat64(qrDaysForward)
		if qDaysForward != "" {
			if err := r.SetQueryParam("daysForward", qDaysForward); err != nil {
				return err
			}
		}

	}

	if o.DaysSkip != nil {

		// query param daysSkip
		var qrDaysSkip float64
		if o.DaysSkip != nil {
			qrDaysSkip = *o.DaysSkip
		}
		qDaysSkip := swag.FormatFloat64(qrDaysSkip)
		if qDaysSkip != "" {
			if err := r.SetQueryParam("daysSkip", qDaysSkip); err != nil {
				return err
			}
		}

	}

	if o.Step != nil {

		// query param step
		var qrStep float64
		if o.Step != nil {
			qrStep = *o.Step
		}
		qStep := swag.FormatFloat64(qrStep)
		if qStep != "" {
			if err := r.SetQueryParam("step", qStep); err != nil {
				return err
			}
		}

	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
