// Code generated by go-swagger; DO NOT EDIT.

package on_call

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIPublicV1TeamTeamOncallScheduleReader is a Reader for the GetAPIPublicV1TeamTeamOncallSchedule structure.
type GetAPIPublicV1TeamTeamOncallScheduleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPublicV1TeamTeamOncallScheduleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIPublicV1TeamTeamOncallScheduleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIPublicV1TeamTeamOncallScheduleOK creates a GetAPIPublicV1TeamTeamOncallScheduleOK with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleOK() *GetAPIPublicV1TeamTeamOncallScheduleOK {
	return &GetAPIPublicV1TeamTeamOncallScheduleOK{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleOK handles this case with default header values.

The on-call schedule for the team
*/
type GetAPIPublicV1TeamTeamOncallScheduleOK struct {
	Payload *models.OnCallAndOverrides
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleOK) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleOK  %+v", 200, o.Payload)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OnCallAndOverrides)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPublicV1TeamTeamOncallScheduleBadRequest creates a GetAPIPublicV1TeamTeamOncallScheduleBadRequest with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleBadRequest() *GetAPIPublicV1TeamTeamOncallScheduleBadRequest {
	return &GetAPIPublicV1TeamTeamOncallScheduleBadRequest{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIPublicV1TeamTeamOncallScheduleBadRequest struct {
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleBadRequest ", 400)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1TeamTeamOncallScheduleUnauthorized creates a GetAPIPublicV1TeamTeamOncallScheduleUnauthorized with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleUnauthorized() *GetAPIPublicV1TeamTeamOncallScheduleUnauthorized {
	return &GetAPIPublicV1TeamTeamOncallScheduleUnauthorized{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIPublicV1TeamTeamOncallScheduleUnauthorized struct {
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleUnauthorized ", 401)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1TeamTeamOncallScheduleForbidden creates a GetAPIPublicV1TeamTeamOncallScheduleForbidden with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleForbidden() *GetAPIPublicV1TeamTeamOncallScheduleForbidden {
	return &GetAPIPublicV1TeamTeamOncallScheduleForbidden{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIPublicV1TeamTeamOncallScheduleForbidden struct {
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleForbidden) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleForbidden ", 403)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1TeamTeamOncallScheduleNotFound creates a GetAPIPublicV1TeamTeamOncallScheduleNotFound with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleNotFound() *GetAPIPublicV1TeamTeamOncallScheduleNotFound {
	return &GetAPIPublicV1TeamTeamOncallScheduleNotFound{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleNotFound handles this case with default header values.

Team not found
*/
type GetAPIPublicV1TeamTeamOncallScheduleNotFound struct {
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleNotFound) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleNotFound ", 404)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1TeamTeamOncallScheduleInternalServerError creates a GetAPIPublicV1TeamTeamOncallScheduleInternalServerError with default headers values
func NewGetAPIPublicV1TeamTeamOncallScheduleInternalServerError() *GetAPIPublicV1TeamTeamOncallScheduleInternalServerError {
	return &GetAPIPublicV1TeamTeamOncallScheduleInternalServerError{}
}

/*GetAPIPublicV1TeamTeamOncallScheduleInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIPublicV1TeamTeamOncallScheduleInternalServerError struct {
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/team/{team}/oncall/schedule][%d] getApiPublicV1TeamTeamOncallScheduleInternalServerError ", 500)
}

func (o *GetAPIPublicV1TeamTeamOncallScheduleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
