// Code generated by go-swagger; DO NOT EDIT.

package on_call

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// NewPatchAPIPublicV1PoliciesPolicyOncallUserParams creates a new PatchAPIPublicV1PoliciesPolicyOncallUserParams object
// with the default values initialized.
func NewPatchAPIPublicV1PoliciesPolicyOncallUserParams() *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	var ()
	return &PatchAPIPublicV1PoliciesPolicyOncallUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithTimeout creates a new PatchAPIPublicV1PoliciesPolicyOncallUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithTimeout(timeout time.Duration) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	var ()
	return &PatchAPIPublicV1PoliciesPolicyOncallUserParams{

		timeout: timeout,
	}
}

// NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithContext creates a new PatchAPIPublicV1PoliciesPolicyOncallUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithContext(ctx context.Context) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	var ()
	return &PatchAPIPublicV1PoliciesPolicyOncallUserParams{

		Context: ctx,
	}
}

// NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithHTTPClient creates a new PatchAPIPublicV1PoliciesPolicyOncallUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAPIPublicV1PoliciesPolicyOncallUserParamsWithHTTPClient(client *http.Client) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	var ()
	return &PatchAPIPublicV1PoliciesPolicyOncallUserParams{
		HTTPClient: client,
	}
}

/*PatchAPIPublicV1PoliciesPolicyOncallUserParams contains all the parameters to send to the API endpoint
for the patch API public v1 policies policy oncall user operation typically these are written to a http.Request
*/
type PatchAPIPublicV1PoliciesPolicyOncallUserParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*Body
	  The take on-call payload

	*/
	Body *models.TakeRequest
	/*Policy
	  The VictorOps policy 'slug'

	*/
	Policy string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithTimeout(timeout time.Duration) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithContext(ctx context.Context) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithHTTPClient(client *http.Client) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithXVOAPIID(xVOAPIID string) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithXVOAPIKey(xVOAPIKey string) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithBody adds the body to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithBody(body *models.TakeRequest) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetBody(body *models.TakeRequest) {
	o.Body = body
}

// WithPolicy adds the policy to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WithPolicy(policy string) *PatchAPIPublicV1PoliciesPolicyOncallUserParams {
	o.SetPolicy(policy)
	return o
}

// SetPolicy adds the policy to the patch API public v1 policies policy oncall user params
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) SetPolicy(policy string) {
	o.Policy = policy
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIPublicV1PoliciesPolicyOncallUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param policy
	if err := r.SetPathParam("policy", o.Policy); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
