// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ContactDeviceAdd The contact device
// swagger:model ContactDeviceAdd
type ContactDeviceAdd struct {

	// chat escalation sound
	ChatEscalationSound string `json:"chat_escalation_sound,omitempty"`

	// device label
	DeviceLabel string `json:"device_label,omitempty"`

	// escalation notification sound
	EscalationNotificationSound string `json:"escalation_notification_sound,omitempty"`

	// resolved notification sound
	ResolvedNotificationSound string `json:"resolved_notification_sound,omitempty"`
}

// Validate validates this contact device add
func (m *ContactDeviceAdd) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContactDeviceAdd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContactDeviceAdd) UnmarshalBinary(b []byte) error {
	var res ContactDeviceAdd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
