// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ContactType contact type
// swagger:model ContactType
type ContactType string

const (

	// ContactTypeEmail captures enum value "email"
	ContactTypeEmail ContactType = "email"

	// ContactTypePhone captures enum value "phone"
	ContactTypePhone ContactType = "phone"
)

// for schema
var contactTypeEnum []interface{}

func init() {
	var res []ContactType
	if err := json.Unmarshal([]byte(`["email","phone"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		contactTypeEnum = append(contactTypeEnum, v)
	}
}

func (m ContactType) validateContactTypeEnum(path, location string, value ContactType) error {
	if err := validate.Enum(path, location, value, contactTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this contact type
func (m ContactType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateContactTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
