// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ContactDescription contact description
// swagger:model ContactDescription
type ContactDescription string

const (

	// ContactDescriptionEmailAddress captures enum value "Email Address"
	ContactDescriptionEmailAddress ContactDescription = "Email Address"

	// ContactDescriptionPhoneNumber captures enum value "Phone Number"
	ContactDescriptionPhoneNumber ContactDescription = "Phone Number"
)

// for schema
var contactDescriptionEnum []interface{}

func init() {
	var res []ContactDescription
	if err := json.Unmarshal([]byte(`["Email Address","Phone Number"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		contactDescriptionEnum = append(contactDescriptionEnum, v)
	}
}

func (m ContactDescription) validateContactDescriptionEnum(path, location string, value ContactDescription) error {
	if err := validate.Enum(path, location, value, contactDescriptionEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this contact description
func (m ContactDescription) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateContactDescriptionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
