// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteUserPayload The information about what to do with the deleted user
// swagger:model DeleteUserPayload
type DeleteUserPayload struct {

	// The user to take the place of the deleted user in escalations
	// Required: true
	Replacement *string `json:"replacement"`
}

// Validate validates this delete user payload
func (m *DeleteUserPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplacement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteUserPayload) validateReplacement(formats strfmt.Registry) error {

	if err := validate.Required("replacement", "body", m.Replacement); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeleteUserPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteUserPayload) UnmarshalBinary(b []byte) error {
	var res DeleteUserPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
