// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetAPIPublicV1OncallCurrentOKBody get Api public v1 oncall current o k body
// swagger:model getApiPublicV1OncallCurrentOKBody
type GetAPIPublicV1OncallCurrentOKBody struct {

	// teams on call
	TeamsOnCall []*OnCallTeamsResource `json:"teamsOnCall"`
}

// Validate validates this get Api public v1 oncall current o k body
func (m *GetAPIPublicV1OncallCurrentOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTeamsOnCall(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAPIPublicV1OncallCurrentOKBody) validateTeamsOnCall(formats strfmt.Registry) error {

	if swag.IsZero(m.TeamsOnCall) { // not required
		return nil
	}

	for i := 0; i < len(m.TeamsOnCall); i++ {
		if swag.IsZero(m.TeamsOnCall[i]) { // not required
			continue
		}

		if m.TeamsOnCall[i] != nil {
			if err := m.TeamsOnCall[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("teamsOnCall" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetAPIPublicV1OncallCurrentOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAPIPublicV1OncallCurrentOKBody) UnmarshalBinary(b []byte) error {
	var res GetAPIPublicV1OncallCurrentOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
