// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostAPIPublicV1ProfileUsernamePoliciesOKBody post Api public v1 profile username policies o k body
// swagger:model postApiPublicV1ProfileUsernamePoliciesOKBody
type PostAPIPublicV1ProfileUsernamePoliciesOKBody struct {

	// self Url
	SelfURL string `json:"_selfUrl,omitempty"`

	// step
	Step *PagingPolicyStep `json:"step,omitempty"`
}

// Validate validates this post Api public v1 profile username policies o k body
func (m *PostAPIPublicV1ProfileUsernamePoliciesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStep(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostAPIPublicV1ProfileUsernamePoliciesOKBody) validateStep(formats strfmt.Registry) error {

	if swag.IsZero(m.Step) { // not required
		return nil
	}

	if m.Step != nil {
		if err := m.Step.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("step")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostAPIPublicV1ProfileUsernamePoliciesOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAPIPublicV1ProfileUsernamePoliciesOKBody) UnmarshalBinary(b []byte) error {
	var res PostAPIPublicV1ProfileUsernamePoliciesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
