// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TeamDetail Some info about the team
// swagger:model TeamDetail
type TeamDetail struct {

	// members Url
	MembersURL string `json:"_membersUrl,omitempty"`

	// policies Url
	PoliciesURL string `json:"_policiesUrl,omitempty"`

	// self Url
	SelfURL string `json:"_selfUrl,omitempty"`

	// is default team
	IsDefaultTeam bool `json:"isDefaultTeam,omitempty"`

	// member count
	MemberCount float64 `json:"memberCount,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// version
	Version float64 `json:"version,omitempty"`
}

// Validate validates this team detail
func (m *TeamDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TeamDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamDetail) UnmarshalBinary(b []byte) error {
	var res TeamDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
