// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserLogAdjustedTotal user log adjusted total
// swagger:model userLogAdjustedTotal
type UserLogAdjustedTotal struct {

	// hours
	Hours float64 `json:"hours,omitempty"`

	// minutes
	Minutes float64 `json:"minutes,omitempty"`
}

// Validate validates this user log adjusted total
func (m *UserLogAdjustedTotal) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserLogAdjustedTotal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserLogAdjustedTotal) UnmarshalBinary(b []byte) error {
	var res UserLogAdjustedTotal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
