// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UserLog user log
// swagger:model UserLog
type UserLog struct {

	// adjusted total
	AdjustedTotal *UserLogAdjustedTotal `json:"adjustedTotal,omitempty"`

	// log
	Log []*OnCallInterval `json:"log"`

	// total
	Total *UserLogTotal `json:"total,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this user log
func (m *UserLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdjustedTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserLog) validateAdjustedTotal(formats strfmt.Registry) error {

	if swag.IsZero(m.AdjustedTotal) { // not required
		return nil
	}

	if m.AdjustedTotal != nil {
		if err := m.AdjustedTotal.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("adjustedTotal")
			}
			return err
		}
	}

	return nil
}

func (m *UserLog) validateLog(formats strfmt.Registry) error {

	if swag.IsZero(m.Log) { // not required
		return nil
	}

	for i := 0; i < len(m.Log); i++ {
		if swag.IsZero(m.Log[i]) { // not required
			continue
		}

		if m.Log[i] != nil {
			if err := m.Log[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("log" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UserLog) validateTotal(formats strfmt.Registry) error {

	if swag.IsZero(m.Total) { // not required
		return nil
	}

	if m.Total != nil {
		if err := m.Total.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("total")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserLog) UnmarshalBinary(b []byte) error {
	var res UserLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
