// Code generated by go-swagger; DO NOT EDIT.

package reporting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIReportingV2IncidentsReader is a Reader for the GetAPIReportingV2Incidents structure.
type GetAPIReportingV2IncidentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIReportingV2IncidentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIReportingV2IncidentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIReportingV2IncidentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIReportingV2IncidentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIReportingV2IncidentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIReportingV2IncidentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIReportingV2IncidentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIReportingV2IncidentsOK creates a GetAPIReportingV2IncidentsOK with default headers values
func NewGetAPIReportingV2IncidentsOK() *GetAPIReportingV2IncidentsOK {
	return &GetAPIReportingV2IncidentsOK{}
}

/*GetAPIReportingV2IncidentsOK handles this case with default header values.

The list of incidents matching the request filters
*/
type GetAPIReportingV2IncidentsOK struct {
	Payload *models.ActiveIncidentList
}

func (o *GetAPIReportingV2IncidentsOK) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsOK  %+v", 200, o.Payload)
}

func (o *GetAPIReportingV2IncidentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActiveIncidentList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIReportingV2IncidentsBadRequest creates a GetAPIReportingV2IncidentsBadRequest with default headers values
func NewGetAPIReportingV2IncidentsBadRequest() *GetAPIReportingV2IncidentsBadRequest {
	return &GetAPIReportingV2IncidentsBadRequest{}
}

/*GetAPIReportingV2IncidentsBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIReportingV2IncidentsBadRequest struct {
}

func (o *GetAPIReportingV2IncidentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsBadRequest ", 400)
}

func (o *GetAPIReportingV2IncidentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV2IncidentsUnauthorized creates a GetAPIReportingV2IncidentsUnauthorized with default headers values
func NewGetAPIReportingV2IncidentsUnauthorized() *GetAPIReportingV2IncidentsUnauthorized {
	return &GetAPIReportingV2IncidentsUnauthorized{}
}

/*GetAPIReportingV2IncidentsUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIReportingV2IncidentsUnauthorized struct {
}

func (o *GetAPIReportingV2IncidentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsUnauthorized ", 401)
}

func (o *GetAPIReportingV2IncidentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV2IncidentsForbidden creates a GetAPIReportingV2IncidentsForbidden with default headers values
func NewGetAPIReportingV2IncidentsForbidden() *GetAPIReportingV2IncidentsForbidden {
	return &GetAPIReportingV2IncidentsForbidden{}
}

/*GetAPIReportingV2IncidentsForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIReportingV2IncidentsForbidden struct {
}

func (o *GetAPIReportingV2IncidentsForbidden) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsForbidden ", 403)
}

func (o *GetAPIReportingV2IncidentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV2IncidentsNotFound creates a GetAPIReportingV2IncidentsNotFound with default headers values
func NewGetAPIReportingV2IncidentsNotFound() *GetAPIReportingV2IncidentsNotFound {
	return &GetAPIReportingV2IncidentsNotFound{}
}

/*GetAPIReportingV2IncidentsNotFound handles this case with default header values.

Path not found
*/
type GetAPIReportingV2IncidentsNotFound struct {
}

func (o *GetAPIReportingV2IncidentsNotFound) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsNotFound ", 404)
}

func (o *GetAPIReportingV2IncidentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV2IncidentsInternalServerError creates a GetAPIReportingV2IncidentsInternalServerError with default headers values
func NewGetAPIReportingV2IncidentsInternalServerError() *GetAPIReportingV2IncidentsInternalServerError {
	return &GetAPIReportingV2IncidentsInternalServerError{}
}

/*GetAPIReportingV2IncidentsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIReportingV2IncidentsInternalServerError struct {
}

func (o *GetAPIReportingV2IncidentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v2/incidents][%d] getApiReportingV2IncidentsInternalServerError ", 500)
}

func (o *GetAPIReportingV2IncidentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
