// Code generated by go-swagger; DO NOT EDIT.

package reporting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIReportingV1IncidentsReader is a Reader for the GetAPIReportingV1Incidents structure.
type GetAPIReportingV1IncidentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIReportingV1IncidentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIReportingV1IncidentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIReportingV1IncidentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIReportingV1IncidentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIReportingV1IncidentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIReportingV1IncidentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIReportingV1IncidentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIReportingV1IncidentsOK creates a GetAPIReportingV1IncidentsOK with default headers values
func NewGetAPIReportingV1IncidentsOK() *GetAPIReportingV1IncidentsOK {
	return &GetAPIReportingV1IncidentsOK{}
}

/*GetAPIReportingV1IncidentsOK handles this case with default header values.

The list of incidents matching the request filters
*/
type GetAPIReportingV1IncidentsOK struct {
	Payload []*models.IncidentList
}

func (o *GetAPIReportingV1IncidentsOK) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsOK  %+v", 200, o.Payload)
}

func (o *GetAPIReportingV1IncidentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIReportingV1IncidentsBadRequest creates a GetAPIReportingV1IncidentsBadRequest with default headers values
func NewGetAPIReportingV1IncidentsBadRequest() *GetAPIReportingV1IncidentsBadRequest {
	return &GetAPIReportingV1IncidentsBadRequest{}
}

/*GetAPIReportingV1IncidentsBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIReportingV1IncidentsBadRequest struct {
}

func (o *GetAPIReportingV1IncidentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsBadRequest ", 400)
}

func (o *GetAPIReportingV1IncidentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV1IncidentsUnauthorized creates a GetAPIReportingV1IncidentsUnauthorized with default headers values
func NewGetAPIReportingV1IncidentsUnauthorized() *GetAPIReportingV1IncidentsUnauthorized {
	return &GetAPIReportingV1IncidentsUnauthorized{}
}

/*GetAPIReportingV1IncidentsUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIReportingV1IncidentsUnauthorized struct {
}

func (o *GetAPIReportingV1IncidentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsUnauthorized ", 401)
}

func (o *GetAPIReportingV1IncidentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV1IncidentsForbidden creates a GetAPIReportingV1IncidentsForbidden with default headers values
func NewGetAPIReportingV1IncidentsForbidden() *GetAPIReportingV1IncidentsForbidden {
	return &GetAPIReportingV1IncidentsForbidden{}
}

/*GetAPIReportingV1IncidentsForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIReportingV1IncidentsForbidden struct {
}

func (o *GetAPIReportingV1IncidentsForbidden) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsForbidden ", 403)
}

func (o *GetAPIReportingV1IncidentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV1IncidentsNotFound creates a GetAPIReportingV1IncidentsNotFound with default headers values
func NewGetAPIReportingV1IncidentsNotFound() *GetAPIReportingV1IncidentsNotFound {
	return &GetAPIReportingV1IncidentsNotFound{}
}

/*GetAPIReportingV1IncidentsNotFound handles this case with default header values.

Path not found
*/
type GetAPIReportingV1IncidentsNotFound struct {
}

func (o *GetAPIReportingV1IncidentsNotFound) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsNotFound ", 404)
}

func (o *GetAPIReportingV1IncidentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIReportingV1IncidentsInternalServerError creates a GetAPIReportingV1IncidentsInternalServerError with default headers values
func NewGetAPIReportingV1IncidentsInternalServerError() *GetAPIReportingV1IncidentsInternalServerError {
	return &GetAPIReportingV1IncidentsInternalServerError{}
}

/*GetAPIReportingV1IncidentsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIReportingV1IncidentsInternalServerError struct {
}

func (o *GetAPIReportingV1IncidentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-reporting/v1/incidents][%d] getApiReportingV1IncidentsInternalServerError ", 500)
}

func (o *GetAPIReportingV1IncidentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
