// Code generated by go-swagger; DO NOT EDIT.

package user_paging_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIPublicV1UserUserPoliciesParams creates a new GetAPIPublicV1UserUserPoliciesParams object
// with the default values initialized.
func NewGetAPIPublicV1UserUserPoliciesParams() *GetAPIPublicV1UserUserPoliciesParams {
	var ()
	return &GetAPIPublicV1UserUserPoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIPublicV1UserUserPoliciesParamsWithTimeout creates a new GetAPIPublicV1UserUserPoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIPublicV1UserUserPoliciesParamsWithTimeout(timeout time.Duration) *GetAPIPublicV1UserUserPoliciesParams {
	var ()
	return &GetAPIPublicV1UserUserPoliciesParams{

		timeout: timeout,
	}
}

// NewGetAPIPublicV1UserUserPoliciesParamsWithContext creates a new GetAPIPublicV1UserUserPoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIPublicV1UserUserPoliciesParamsWithContext(ctx context.Context) *GetAPIPublicV1UserUserPoliciesParams {
	var ()
	return &GetAPIPublicV1UserUserPoliciesParams{

		Context: ctx,
	}
}

// NewGetAPIPublicV1UserUserPoliciesParamsWithHTTPClient creates a new GetAPIPublicV1UserUserPoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIPublicV1UserUserPoliciesParamsWithHTTPClient(client *http.Client) *GetAPIPublicV1UserUserPoliciesParams {
	var ()
	return &GetAPIPublicV1UserUserPoliciesParams{
		HTTPClient: client,
	}
}

/*GetAPIPublicV1UserUserPoliciesParams contains all the parameters to send to the API endpoint
for the get API public v1 user user policies operation typically these are written to a http.Request
*/
type GetAPIPublicV1UserUserPoliciesParams struct {

	/*XVOAPIID
	  Your API ID

	*/
	XVOAPIID string
	/*XVOAPIKey
	  Your API Key

	*/
	XVOAPIKey string
	/*User
	  The VictorOps user ID

	*/
	User string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithTimeout(timeout time.Duration) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithContext(ctx context.Context) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithHTTPClient(client *http.Client) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXVOAPIID adds the xVOAPIID to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithXVOAPIID(xVOAPIID string) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetXVOAPIID(xVOAPIID)
	return o
}

// SetXVOAPIID adds the xVOApiId to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetXVOAPIID(xVOAPIID string) {
	o.XVOAPIID = xVOAPIID
}

// WithXVOAPIKey adds the xVOAPIKey to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithXVOAPIKey(xVOAPIKey string) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetXVOAPIKey(xVOAPIKey)
	return o
}

// SetXVOAPIKey adds the xVOApiKey to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetXVOAPIKey(xVOAPIKey string) {
	o.XVOAPIKey = xVOAPIKey
}

// WithUser adds the user to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) WithUser(user string) *GetAPIPublicV1UserUserPoliciesParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the get API public v1 user user policies params
func (o *GetAPIPublicV1UserUserPoliciesParams) SetUser(user string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIPublicV1UserUserPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-VO-Api-Id
	if err := r.SetHeaderParam("X-VO-Api-Id", o.XVOAPIID); err != nil {
		return err
	}

	// header param X-VO-Api-Key
	if err := r.SetHeaderParam("X-VO-Api-Key", o.XVOAPIKey); err != nil {
		return err
	}

	// path param user
	if err := r.SetPathParam("user", o.User); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
