// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/erikvanbrakel/terraform-provider-victorops/go-victorops-swagger/models"
)

// GetAPIPublicV1AlertsUUIDReader is a Reader for the GetAPIPublicV1AlertsUUID structure.
type GetAPIPublicV1AlertsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPublicV1AlertsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIPublicV1AlertsUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAPIPublicV1AlertsUUIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAPIPublicV1AlertsUUIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAPIPublicV1AlertsUUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAPIPublicV1AlertsUUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAPIPublicV1AlertsUUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIPublicV1AlertsUUIDOK creates a GetAPIPublicV1AlertsUUIDOK with default headers values
func NewGetAPIPublicV1AlertsUUIDOK() *GetAPIPublicV1AlertsUUIDOK {
	return &GetAPIPublicV1AlertsUUIDOK{}
}

/*GetAPIPublicV1AlertsUUIDOK handles this case with default header values.

The alert, if found.

*/
type GetAPIPublicV1AlertsUUIDOK struct {
	Payload *models.GetAlertResponse
}

func (o *GetAPIPublicV1AlertsUUIDOK) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidOK  %+v", 200, o.Payload)
}

func (o *GetAPIPublicV1AlertsUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetAlertResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPublicV1AlertsUUIDBadRequest creates a GetAPIPublicV1AlertsUUIDBadRequest with default headers values
func NewGetAPIPublicV1AlertsUUIDBadRequest() *GetAPIPublicV1AlertsUUIDBadRequest {
	return &GetAPIPublicV1AlertsUUIDBadRequest{}
}

/*GetAPIPublicV1AlertsUUIDBadRequest handles this case with default header values.

Problem with the request arguments.  The response payload may include an error message.
*/
type GetAPIPublicV1AlertsUUIDBadRequest struct {
}

func (o *GetAPIPublicV1AlertsUUIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidBadRequest ", 400)
}

func (o *GetAPIPublicV1AlertsUUIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1AlertsUUIDUnauthorized creates a GetAPIPublicV1AlertsUUIDUnauthorized with default headers values
func NewGetAPIPublicV1AlertsUUIDUnauthorized() *GetAPIPublicV1AlertsUUIDUnauthorized {
	return &GetAPIPublicV1AlertsUUIDUnauthorized{}
}

/*GetAPIPublicV1AlertsUUIDUnauthorized handles this case with default header values.

Authentication parameters missing
*/
type GetAPIPublicV1AlertsUUIDUnauthorized struct {
}

func (o *GetAPIPublicV1AlertsUUIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidUnauthorized ", 401)
}

func (o *GetAPIPublicV1AlertsUUIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1AlertsUUIDForbidden creates a GetAPIPublicV1AlertsUUIDForbidden with default headers values
func NewGetAPIPublicV1AlertsUUIDForbidden() *GetAPIPublicV1AlertsUUIDForbidden {
	return &GetAPIPublicV1AlertsUUIDForbidden{}
}

/*GetAPIPublicV1AlertsUUIDForbidden handles this case with default header values.

Authentication failed or rate-limit reached
*/
type GetAPIPublicV1AlertsUUIDForbidden struct {
}

func (o *GetAPIPublicV1AlertsUUIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidForbidden ", 403)
}

func (o *GetAPIPublicV1AlertsUUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1AlertsUUIDNotFound creates a GetAPIPublicV1AlertsUUIDNotFound with default headers values
func NewGetAPIPublicV1AlertsUUIDNotFound() *GetAPIPublicV1AlertsUUIDNotFound {
	return &GetAPIPublicV1AlertsUUIDNotFound{}
}

/*GetAPIPublicV1AlertsUUIDNotFound handles this case with default header values.

User not found
*/
type GetAPIPublicV1AlertsUUIDNotFound struct {
}

func (o *GetAPIPublicV1AlertsUUIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidNotFound ", 404)
}

func (o *GetAPIPublicV1AlertsUUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAPIPublicV1AlertsUUIDInternalServerError creates a GetAPIPublicV1AlertsUUIDInternalServerError with default headers values
func NewGetAPIPublicV1AlertsUUIDInternalServerError() *GetAPIPublicV1AlertsUUIDInternalServerError {
	return &GetAPIPublicV1AlertsUUIDInternalServerError{}
}

/*GetAPIPublicV1AlertsUUIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIPublicV1AlertsUUIDInternalServerError struct {
}

func (o *GetAPIPublicV1AlertsUUIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-public/v1/alerts/{uuid}][%d] getApiPublicV1AlertsUuidInternalServerError ", 500)
}

func (o *GetAPIPublicV1AlertsUUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
